#apiVersion: backstage.io/v1alpha1
#kind: Component
#metadata:
#  name: backstage-local
#  description: An example of a Backstage application.
#  # Example for optional annotations
#  # annotations:
#  #   github.com/project-slug: backstage/backstage
#  #   backstage.io/techdocs-ref: dir:.
#spec:
#  type: website
#  owner: john@example.com
#  lifecycle: experimental

#apiVersion: backstage.io/v1alpha1
#kind: Component
#metadata:
#  name: plugin-argocd-autopilot
#spec:
#  lifecycle: production
#  owner: my-team
#  type: service
#---
# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   annotations:
#     argocd/app-selector: "app.kubernetes.io/managed-by=argocd-autopilot"
#   name: argocd-autopilot
# spec:
#   lifecycle: production
#   owner: my-team
#   type: service
#
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
<<<<<<< HEAD
  name: gcp-folder
=======
  annotations:
    'backstage.io/kubernetes-id': dice-roller
  name: kubernetes
>>>>>>> 50ef37e53231cded186893729d0ccbb996c7e9bc
spec:
  lifecycle: production
  owner: mirage-team
  type: service

