
steps:
- name: node:14
  entrypoint: yarn
  args: ['install']
- name: node:14
  entrypoint: yarn
  args:
  - '-c'
  - |
    cd packages/backend/ && \
    backstage-cli package build --role backend

- name: "gcr.io/kaniko-project/executor:latest"
  args:
    - --destination=us-central1-docker.pkg.dev/px-mike-project-hje/backstage/backstage:latest
    - --dockerfile=./packages/backend
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=manifests/deployment.yaml
  - --image=gcr.io/px-mike-project-hje/backstage:latest
  - --location=us-central1
  - --cluster=primary-cluster

