
steps:
- name: node:14
  entrypoint: yarn
  args: ['install']
- name: node:14
  entrypoint: yarn
  args: ['backstage-cli package build --role backend']
- name: "gcr.io/kaniko-project/executor:latest"
  # args: ['build', '-t', 'us-central1-docker.pkg.dev/px-mike-project-hje/px-backstage-dev/backstage', '.']
  args:
    - --destination=us-central1-docker.pkg.dev/px-mike-project-hje/backstage/backstage:latest
    - --context=./packages/backend
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'us-central1-docker.pkg.dev/px-mike-project-hje/px-backstage-dev/backstage']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=charts/deployment.yaml
  - --image=gcr.io/px-mike-project-hje/backstage:latest
  - --location=us-central1
  - --cluster=primary-cluster

