
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backstage-backendconfig
  namespace: backstage
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 7007
  securityPolicy:
    name: us-only
  
