
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: gke-frontendconfig
  namespace: backstage
spec:
  sslPolicy: tls-12
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANTNTLY_DEFAULT

