
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: backstage-cert
spec:
  domains:
    - backstage-mike.px.igniteme.dev

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-ingress
  namespace: backstage
  annotations:
    kubernetes.io/ingress.global-static-ip-name: backstage-ip
    networking.gke.io/managed-certificates: backstage-cert
    networking.gke.io/v1beta1.FrontendConfig: gke-frontendconfig
spec:
  rules:
  - host: backstage-mike.px.igniteme.dev
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backstage
            port:
              number: 443

