
apiVersion: batch/v1
kind: Job
metadata:
  name: backstage-job
spec:
  template:
    metadata:
      name: backstage-job
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage-sa
      containers:
      - name: backstage-job
        image: postgres:15.1-alpine
        command: ["psql"]
        args: 
          - "-U postgres"
          - "-d postgres"
          - "-c 'GRANT SELECT ON postgres TO postgres'"
        env:
          - name: DB_HOST
            value: "localhost"
          - name: DB_DATABASE
            value: "postgres"
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-log_debug_stdout"
          - "-instances=px-mike-project-hje:us-central1:pg-database=tcp:5432"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
      restartPolicy: Never
  backoffLimit: 4

